# Generated by Django 5.0 on 2024-04-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_comentario_deporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='customuser',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
