# Generated by Django 5.0 on 2024-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_comentario_usuarios_que_dieron_like_foro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
