# Generated by Django 5.0 on 2024-04-13 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_foro_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='usuarios_que_dieron_like',
            field=models.ManyToManyField(blank=True, related_name='likes_foro', to=settings.AUTH_USER_MODEL),
        ),
    ]
